name: "HomeOps"
description: "Autopilot for Home Assistant: Doctor (read-only) + Safe Change Engine (coming soon)."
version: "0.0.1"
slug: "homeops"
startup: services
init: false

arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

ingress: true
ingress_port: 8000
panel_icon: mdi:home-automation
panel_title: HomeOps

homeassistant_api: true
# hassio_api: true  # enable later when you need Supervisor endpoints

options: {}
schema: {}
